---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-ssl
spec:
  tls:
  - hosts:
    - kube-book.com
    secretName: kube-book-secret
  rules:
  - host: kube-book.com
    http:
      paths:
      - path: /
        backend:
          serviceName: s1
          servicePort: 80
