---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ssl
spec:
  tls:
  - hosts:
    - kube-book.com
    secretName: kube-book-secret
  rules:
  - host: kube-book.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: s1
            port: 
              number: 80